package com.compi.frontend;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JTabbedPane;
import javax.swing.JTextArea;
import javax.swing.JTextPane;
import javax.swing.event.CaretEvent;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;
import javax.swing.text.StyledDocument;

/**
 *
 * @author michael
 */
public class EditorPanel extends JPanel {

    private JTextPane codeTextArea;
    private JTextArea pigLatinConsole;
    private JTextArea executionConsole;
    private JTextArea c3dConsole;
    private JTabbedPane consoleTabbedPane;
    private JLabel statusLabel;
    private JButton compileButton;
    private LineNumberComponent lineNumberComponent;
    //private final Compiler compiler = new Compiler();
    private String result = "";
    private boolean isUpdatingHighlight = false;
    private Color colorSecciones;
    private Color colorKeywords;
    private Color colorTipos;
    private Color colorCadenas;
    private Color colorComentarios;

    /**
     * Creates new form EditorPanel
     */
    public EditorPanel() {
        initComponents();
        initCustomEditor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 704, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 387, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    public String getCodeText() {
        return codeTextArea.getText();
    }

    public void setCodeText(String text) {
        codeTextArea.setText(text);
    }

    public String getResult() {
        return result;
    }

    public void setResult(String text) {
        this.result = text;
    }

    // ===== Terminal de salida =====

    public String getTerminalText() {
        return executionConsole != null ? executionConsole.getText() : "";
    }

    public void setTerminalText(String text) {
        if (executionConsole != null) {
            executionConsole.setText(text);
        }
    }

    public void appendTerminal(String text) {
        if (executionConsole != null) {
            executionConsole.append(text + "\n");
        }
    }

    // ===== Consola Código de 3 direcciones =====

    public String getC3DText() {
        return c3dConsole != null ? c3dConsole.getText() : "";
    }

    public void setC3DText(String text) {
        if (c3dConsole != null) {
            c3dConsole.setText(text);
        }
    }

    public void appendC3D(String text) {
        if (c3dConsole != null) {
            c3dConsole.append(text + "\n");
        }
    }

    /**
     * Muestra la pestaña "Código 3D" en las consolas del editor.
     */
    public void showC3DTab() {
        if (consoleTabbedPane != null) {
            int index = consoleTabbedPane.indexOfTab("Código 3D");
            if (index >= 0) {
                consoleTabbedPane.setSelectedIndex(index);
            }
        }
    }

    /**
     * Método de compatibilidad para establecer texto en las consolas desde
     * MainWindow.
     *
     * @param text El texto a mostrar.
     */
    public void setConsoleTextArea(String text) {
        if (pigLatinConsole != null) {
            pigLatinConsole.setText(text);
        }
        if (executionConsole != null) {
            executionConsole.setText(text);
        }
    }

    /**
     * Método de compatibilidad para imprimir en la consola de PigLatin.
     */
    public void printToConsole(String text) {
        if (pigLatinConsole != null) {
            pigLatinConsole.setForeground(Color.GREEN);
            pigLatinConsole.append(text + "\n");
        }
    }

    /**
     * Inicializa los componentes del editor de código, consola, números de
     * línea, botón compilar y barra de estado.
     */
    private void initCustomEditor() {
        this.setLayout(new BorderLayout());

        inicializarColores();

        Color backgroundGray = new Color(240, 240, 240);
        this.setBackground(backgroundGray);

        // Editor de código fuente (Área superior)
        codeTextArea = new JTextPane();
        codeTextArea.setFont(new Font("Monospaced", Font.PLAIN, 14));
        codeTextArea.setBackground(new Color(255, 255, 255));

        lineNumberComponent = new LineNumberComponent(codeTextArea);

        JScrollPane codeScrollPane = new JScrollPane(codeTextArea);
        codeScrollPane.setRowHeaderView(lineNumberComponent);
        codeScrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);
        codeScrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        codeScrollPane.setBackground(backgroundGray);
        codeScrollPane.getViewport().setBackground(new Color(255, 255, 255));

        // Consola Pestaña 1: PigLatin
        pigLatinConsole = new JTextArea();
        pigLatinConsole.setFont(new Font("Monospaced", Font.PLAIN, 13));
        pigLatinConsole.setEditable(false);
        pigLatinConsole.setBackground(new Color(30, 30, 30));
        pigLatinConsole.setForeground(new Color(220, 220, 220));
        JScrollPane pigLatinScroll = new JScrollPane(pigLatinConsole);

        // Consola Pestaña 2: Ejecución (terminal de salida del programa)
        executionConsole = new JTextArea();
        executionConsole.setFont(new Font("Monospaced", Font.PLAIN, 13));
        executionConsole.setEditable(false);
        executionConsole.setBackground(new Color(30, 30, 30));
        executionConsole.setForeground(new Color(220, 220, 220));
        JScrollPane executionScroll = new JScrollPane(executionConsole);

        // Consola Pestaña 3: Código de tres direcciones
        c3dConsole = new JTextArea();
        c3dConsole.setFont(new Font("Monospaced", Font.PLAIN, 13));
        c3dConsole.setEditable(false);
        c3dConsole.setBackground(new Color(25, 25, 35));
        c3dConsole.setForeground(new Color(180, 220, 255));
        JScrollPane c3dScroll = new JScrollPane(c3dConsole);

        // Panel con pestañas para la consola
        consoleTabbedPane = new JTabbedPane();
        consoleTabbedPane.addTab("Terminal", executionScroll);
        consoleTabbedPane.addTab("PigLatin", pigLatinScroll);
        consoleTabbedPane.addTab("Código 3D", c3dScroll);
        consoleTabbedPane.setBorder(BorderFactory.createTitledBorder(" Consola de Resultados "));

        // Barra de estado y botón compilar (Área inferior)
        JPanel statusPanel = new JPanel(new BorderLayout());
        statusPanel.setBackground(backgroundGray);
        statusPanel.setBorder(BorderFactory.createEmptyBorder(2, 5, 2, 5));

        compileButton = new JButton("Compilar y Ejecutar");
        compileButton.setBackground(new Color(46, 139, 87));
        compileButton.setForeground(Color.WHITE);
        compileButton.setCursor(new Cursor(Cursor.HAND_CURSOR));
        compileButton.addActionListener(e -> compileButtonActionPerformed(e));

        JPanel leftStatusPanel = new JPanel(new FlowLayout(FlowLayout.LEFT, 0, 0));
        leftStatusPanel.setOpaque(false);
        leftStatusPanel.add(compileButton);
        statusPanel.add(leftStatusPanel, BorderLayout.WEST);

        statusLabel = new JLabel("Línea: 1 | Columna: 1");
        statusLabel.setFont(new Font("SansSerif", Font.PLAIN, 12));
        statusLabel.setForeground(Color.BLACK);
        statusPanel.add(statusLabel, BorderLayout.EAST);

        // SplitPane principal separando Editor y Consola Tabulada
        JSplitPane splitPane = new JSplitPane(JSplitPane.VERTICAL_SPLIT, codeScrollPane, consoleTabbedPane);
        splitPane.setResizeWeight(0.75);
        splitPane.setDividerLocation(350);
        splitPane.setBackground(backgroundGray);

        this.add(splitPane, BorderLayout.CENTER);
        this.add(statusPanel, BorderLayout.SOUTH);

        // Listener para coloreado sintáctico dinámico
        codeTextArea.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                triggerHighlight();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                triggerHighlight();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                triggerHighlight();
            }
        });

        // Listener para posición del cursor
        codeTextArea.addCaretListener((CaretEvent e) -> {
            int lineNumber = 1;
            int columnNumber = 1;
            try {
                int caretPos = codeTextArea.getCaretPosition();
                String text = codeTextArea.getText();
                if (caretPos <= text.length()) {
                    for (int i = 0; i < caretPos; i++) {
                        if (text.charAt(i) == '\n') {
                            lineNumber++;
                            columnNumber = 1;
                        } else {
                            columnNumber++;
                        }
                    }
                }
            } catch (Exception ex) {
                // Manejo de excepciones de posición
            }
            statusLabel.setText("Línea: " + lineNumber + " | Columna: " + columnNumber);
        });
    }

    private void inicializarColores() {
        colorSecciones = new Color(128, 0, 128);
        colorKeywords = new Color(0, 0, 255);
        colorTipos = new Color(0, 128, 128);
        colorCadenas = new Color(0, 128, 0);
        colorComentarios = new Color(128, 128, 128);
    }

    private void triggerHighlight() {
        if (isUpdatingHighlight) {
            return;
        }
        isUpdatingHighlight = true;

        javax.swing.SwingUtilities.invokeLater(() -> {
            applySyntaxHighlighting();
            isUpdatingHighlight = false;
        });
    }

    private void applySyntaxHighlighting() {
        StyledDocument doc = codeTextArea.getStyledDocument();
        String text = codeTextArea.getText();

        Style defaultStyle = StyleContext.getDefaultStyleContext().getStyle(StyleContext.DEFAULT_STYLE);
        StyleConstants.setForeground(defaultStyle, Color.BLACK);
        doc.setCharacterAttributes(0, text.length(), defaultStyle, true);

        coloringRegex(doc, text, "\\b(VARIABILES>|MUNERA>|MAIOR>)\\b", colorSecciones, true);
        coloringRegex(doc, text, "\\b(structura|ratio|actio|si|sino|dum|facere|per|reddere|finis|perge|interrumpe|verum|falsus)\\b", colorKeywords, true);
        coloringRegex(doc, text, "\\b(numerus|textum|decimalis|littera)\\b", colorTipos, false);
        coloringRegex(doc, text, "\"[^\"]*\"", colorCadenas, false);
        coloringRegex(doc, text, "//.*", colorComentarios, false);
        coloringRegex(doc, text, "##[\\s\\S]*?##", colorComentarios, false);
    }

    private void coloringRegex(StyledDocument doc, String text, String regex, Color color, boolean bold) {
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(text);

        Style style = doc.addStyle("Style_" + regex.hashCode(), null);
        StyleConstants.setForeground(style, color);
        StyleConstants.setBold(style, bold);

        while (matcher.find()) {
            doc.setCharacterAttributes(matcher.start(), matcher.end() - matcher.start(), style, false);
        }
    }

    private void compileButtonActionPerformed(ActionEvent evt) {
      /*  pigLatinConsole.setText("");
        executionConsole.setText("");
        String codigoFuente = codeTextArea.getText();

        if (codigoFuente.trim().isEmpty()) {
            pigLatinConsole.setForeground(Color.RED);
            pigLatinConsole.setText("Error: El editor está vacío.");
            executionConsole.setForeground(Color.RED);
            executionConsole.setText("Error: El editor está vacío.");
            return;
        }

        try {
            String pigLatinResult = compiler.parseCode(codigoFuente);
            pigLatinConsole.setForeground(new Color(0, 230, 118));
            pigLatinConsole.setText(pigLatinResult != null ? pigLatinResult : "");

            if (compiler.getCompilationErrors().isEmpty()) {
                String humanResult = compiler.getHumanTranslatedText();

                executionConsole.setForeground(new Color(100, 210, 255));
                executionConsole.setText(humanResult != null && !humanResult.isEmpty()
                        ? humanResult 
                        : "Ejecución finalizada con éxito (Sin salida por consola).");
            } else {
                executionConsole.setForeground(Color.ORANGE);
                executionConsole.setText("No se puede ejecutar debido a errores en el código:\n" + compiler.getCompilationErrors());
            }

        } catch (Exception ex) {
            pigLatinConsole.setForeground(Color.RED);
            pigLatinConsole.setText("Error en la traducción:\n" + ex.getMessage());

            executionConsole.setForeground(Color.RED);
            executionConsole.setText("Error en la ejecución:\n" + ex.getMessage());
        }*/
    }

    public void clearConsole() {
        pigLatinConsole.setText("");
        executionConsole.setText("");
        if (c3dConsole != null) {
            c3dConsole.setText("");
        }
    }
/*
    public SymbolTable getSymbolTable() {
        return compiler.getSymbolTable();
    }

    public List<CompilationError> getCompilationErrors() {
        return compiler.getCompilationErrors();
    }

    public String getLastDotCode() {
        return compiler.getLastDotCode();
    }

    public List<StackState> getLastStackSteps() {
        return compiler.getLastStackSteps();
    }*/
}
