package com.compi.frontend;

import com.compi.backend.errors.CompilationError;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 * Vista de la tabla de errores del compilador.
 *
 * Clasifica los errores por fase (lexico, sintactico, semantico) y colorea la
 * columna de tipo segun la gravedad.
 */
public class ErrorTablePanel extends javax.swing.JPanel {

    private JTable errorTable;
    private DefaultTableModel tableModel;
    private JScrollPane scrollPane;
    private JLabel emptyMessageLabel;

    /**
     * Creates new form ErrorTablePanel
     */
    public ErrorTablePanel() {
        initComponents();
        initCustomComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private void initCustomComponents() {
        setLayout(new BorderLayout());

        tableModel = new DefaultTableModel(
                new Object[]{"#", "Tipo", "Línea", "Col.", "Descripción"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        errorTable = new JTable(tableModel);
        errorTable.setFont(UiTheme.mono(12));
        errorTable.setRowHeight(24);
        errorTable.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        errorTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        errorTable.setBackground(UiTheme.toolWindowBg());
        errorTable.setForeground(UiTheme.fg());
        errorTable.setGridColor(UiTheme.separator());
        errorTable.getTableHeader().setFont(UiTheme.sansBold(12));
        errorTable.getTableHeader().setReorderingAllowed(false);

        int[] widths = {34, 100, 52, 52, 240};
        for (int i = 0; i < widths.length; i++) {
            errorTable.getColumnModel().getColumn(i).setPreferredWidth(widths[i]);
        }

        DefaultTableCellRenderer typeRenderer = new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                                                           boolean isSelected, boolean hasFocus,
                                                           int row, int column) {
                Component comp = super.getTableCellRendererComponent(
                        table, value, isSelected, hasFocus, row, column);
                if (!isSelected) {
                    comp.setForeground(colorForType(String.valueOf(value)));
                }
                setHorizontalAlignment(SwingConstants.CENTER);
                return comp;
            }
        };
        errorTable.getColumnModel().getColumn(1).setCellRenderer(typeRenderer);

        emptyMessageLabel = new JLabel("Sin errores de compilación", SwingConstants.CENTER);
        emptyMessageLabel.setFont(UiTheme.sans(12));
        emptyMessageLabel.setForeground(UiTheme.dim());
        emptyMessageLabel.setBorder(UiTheme.pad(20, 0, 20, 0));

        scrollPane = new JScrollPane(errorTable);
        scrollPane.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        scrollPane.setVisible(false);

        add(scrollPane, BorderLayout.CENTER);
        add(emptyMessageLabel, BorderLayout.CENTER);
    }

    private Color colorForType(String type) {
        return switch (type) {
            case "LEXICO" -> UiTheme.warning();
            case "SINTACTICO" -> UiTheme.error();
            case "SEMANTICO" -> new Color(0xDB5860).brighter();
            default -> UiTheme.dim();
        };
    }

    // ====================== API ======================

    /**
     * Carga la lista de errores.
     */
    public void loadErrors(List<CompilationError> errors) {
        tableModel.setRowCount(0);
        if (errors == null || errors.isEmpty()) {
            scrollPane.setVisible(false);
            emptyMessageLabel.setVisible(true);
            emptyMessageLabel.setText("Sin errores de compilación");
            revalidate();
            repaint();
            return;
        }
        int i = 1;
        for (CompilationError e : errors) {
            tableModel.addRow(new Object[]{
                    i++,
                    e.getType(),
                    e.getLine(),
                    e.getColumn(),
                    e.getMessage()
            });
        }
        scrollPane.setVisible(true);
        emptyMessageLabel.setVisible(false);
        revalidate();
        repaint();
    }

    public JTable getErrorTable() {
        return errorTable;
    }

    public int getErrorCount() {
        return tableModel.getRowCount();
    }

    /**
     * Devuelve el error de la fila seleccionada, o null.
     */
    public CompilationError getSelectedError(List<CompilationError> errors) {
        int row = errorTable.getSelectedRow();
        if (row < 0 || errors == null || row >= errors.size()) {
            return null;
        }
        return errors.get(row);
    }

    /** Limpia la vista. */
    public void clear() {
        loadErrors(null);
    }
}
