package com.compi.frontend;

import codex_latinus.backend.errors.CompilationError;
import java.awt.BorderLayout;
import java.awt.Font;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author michael
 */
public class ErrorTablePanel extends javax.swing.JPanel {

    private JTable errorTable;
    private DefaultTableModel tableModel;
    private JScrollPane scrollPane;
    private JLabel emptyMessageLabel;
    
    
    /**
     * Creates new form ErrorTablePanel
     */
    public ErrorTablePanel() {
        initComponents();
        initCustomComponents();
        loadErrors(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private void initCustomComponents() {
        setLayout(new BorderLayout());

        // Definir columnas para cuando sí haya errores
        String[] columnNames = {"Tipo", "Descripción del Error", "Línea", "Columna"};
        
        tableModel = new DefaultTableModel(columnNames, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        errorTable = new JTable(tableModel);
        scrollPane = new JScrollPane(errorTable);

        // Etiqueta creativa para cuando no hay errores
        emptyMessageLabel = new JLabel(
            "<html><div style='text-align: center;'>"
            + "<h2 style='color: #2e7d32;'>¡Zona Libre de Infracciones!</h2>"
            + "<p style='color: #555;'>Los firewalls biométricos de los Cerdos Tiranos no detectaron errores.</p>"
            + "<p style='color: #777; font-size: 11px;'>El código fuente ha pasado la inspección con éxito 🐷✨</p>"
            + "</div></html>", 
            SwingConstants.CENTER
        );
        emptyMessageLabel.setFont(new Font("Segoe UI", Font.PLAIN, 14));
    }
    
    /**
     * Carga o actualiza la lista de errores en el modelo de la tabla.
     * Si no hay errores, muestra un mensaje creativo en lugar de una tabla vacía.
     */
    public void loadErrors(List<CompilationError> errors) {
        removeAll(); // Limpia el panel actual

        if (errors == null || errors.isEmpty()) {
            // Mostrar mensaje creativo si todo está limpio
            add(emptyMessageLabel, BorderLayout.CENTER);
        } else {
            // Si hay errores, rellenar el modelo y mostrar la tabla
            if (tableModel != null) {
                tableModel.setRowCount(0);
                for (CompilationError err : errors) {
                    Object[] rowData = {
                        err.getType(),
                        err.getMessage(),
                        err.getLine(),
                        err.getColumn()
                    };
                    tableModel.addRow(rowData);
                }
            }
            add(scrollPane, BorderLayout.CENTER);
        }

        revalidate();
        repaint();
    }
}