package com.compi.frontend;

import codex_latinus.backend.Compiler;
import codex_latinus.backend.errors.CompilationError;
import codex_latinus.backend.stack.StackState;
import codex_latinus.backend.symbols.Scope;
import codex_latinus.backend.symbols.Symbol;
import codex_latinus.backend.symbols.SymbolTable;
import java.awt.Color;
import java.awt.Dimension;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author michael
 */
public class MainWindow extends javax.swing.JFrame {

    private static final String navText = "Codex Latinus";
    private final EditorPanel editorPanel = new EditorPanel();
    private Compiler compiler = new Compiler();
    private ParserTreePanel treePanel = new ParserTreePanel();
    private final StackVisualizerPanel stackVisualizerPanel = new StackVisualizerPanel();

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        setTitle("Codex Latinus");
        setMinimumSize(new Dimension(685, 461));
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initStyles();
        navText("");
        initialPanel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidebarPanel = new javax.swing.JPanel();
        menuLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        openFileButton = new javax.swing.JButton();
        saveFileButton = new javax.swing.JButton();
        astButton = new javax.swing.JButton();
        symbolTableButton = new javax.swing.JButton();
        stackButton = new javax.swing.JButton();
        newFileButton = new javax.swing.JButton();
        lexerErrorButton = new javax.swing.JButton();
        sintaxErrorButton1 = new javax.swing.JButton();
        semanticErrorButton1 = new javax.swing.JButton();
        editTextButton = new javax.swing.JButton();
        contentPane = new javax.swing.JPanel();
        navTextLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidebarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuLabel.setText("Menú de opciones");
        menuLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sidebarPanel.add(menuLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 10, 180, -1));
        sidebarPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 160, 10));

        openFileButton.setText("Abrir");
        openFileButton.setBorder(new javax.swing.border.MatteBorder(null));
        openFileButton.setBorderPainted(false);
        openFileButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        openFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileButtonActionPerformed(evt);
            }
        });
        sidebarPanel.add(openFileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 125, 180, 35));

        saveFileButton.setText("Guardar");
        saveFileButton.setBorder(new javax.swing.border.MatteBorder(null));
        saveFileButton.setBorderPainted(false);
        saveFileButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFileButtonActionPerformed(evt);
            }
        });
        sidebarPanel.add(saveFileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 180, 35));

        astButton.setText("AST");
        astButton.setBorder(new javax.swing.border.MatteBorder(null));
        astButton.setBorderPainted(false);
        astButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        astButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                astButtonActionPerformed(evt);
            }
        });
        sidebarPanel.add(astButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 195, 180, 35));

        symbolTableButton.setText("Tabla de símbolos");
        symbolTableButton.setBorder(new javax.swing.border.MatteBorder(null));
        symbolTableButton.setBorderPainted(false);
        symbolTableButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        symbolTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                symbolTableButtonActionPerformed(evt);
            }
        });
        sidebarPanel.add(symbolTableButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 180, 35));

        stackButton.setText("Pila de procesos");
        stackButton.setBorder(new javax.swing.border.MatteBorder(null));
        stackButton.setBorderPainted(false);
        stackButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stackButtonActionPerformed(evt);
            }
        });
        sidebarPanel.add(stackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 180, 35));

        newFileButton.setText("Nuevo");
        newFileButton.setBorder(new javax.swing.border.MatteBorder(null));
        newFileButton.setBorderPainted(false);
        newFileButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFileButtonActionPerformed(evt);
            }
        });
        sidebarPanel.add(newFileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 180, 35));

        lexerErrorButton.setText("Tabla de errores léxicos");
        lexerErrorButton.setBorder(new javax.swing.border.MatteBorder(null));
        lexerErrorButton.setBorderPainted(false);
        lexerErrorButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lexerErrorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lexerErrorButtonActionPerformed(evt);
            }
        });
        sidebarPanel.add(lexerErrorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 265, 180, 35));

        sintaxErrorButton1.setText("Tabla de errores sintácticos");
        sintaxErrorButton1.setBorder(new javax.swing.border.MatteBorder(null));
        sintaxErrorButton1.setBorderPainted(false);
        sintaxErrorButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sintaxErrorButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sintaxErrorButton1ActionPerformed(evt);
            }
        });
        sidebarPanel.add(sintaxErrorButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 180, 35));

        semanticErrorButton1.setText("Tabla de errores semánticos");
        semanticErrorButton1.setBorder(new javax.swing.border.MatteBorder(null));
        semanticErrorButton1.setBorderPainted(false);
        semanticErrorButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        semanticErrorButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semanticErrorButton1ActionPerformed(evt);
            }
        });
        sidebarPanel.add(semanticErrorButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 335, 180, 35));

        editTextButton.setText("Editor de texto");
        editTextButton.setBorder(new javax.swing.border.MatteBorder(null));
        editTextButton.setBorderPainted(false);
        editTextButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editTextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTextButtonActionPerformed(evt);
            }
        });
        sidebarPanel.add(editTextButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 56, 180, 35));

        contentPane.setLayout(new java.awt.BorderLayout());

        navTextLabel.setBackground(new java.awt.Color(0, 0, 0));
        navTextLabel.setForeground(new java.awt.Color(0, 255, 0));
        navTextLabel.setText("jLabel1");
        navTextLabel.setMinimumSize(new java.awt.Dimension(685, 461));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(navTextLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                    .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(navTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFileButtonActionPerformed
        String currentText = editorPanel.getCodeText();

        if (currentText != null && !currentText.trim().isEmpty()) {
            int option = JOptionPane.showConfirmDialog(
                    this,
                    "El editor contiene texto. ¿Desea guardar los cambios antes de crear un nuevo archivo?",
                    "Advertencia - Codex Latinus",
                    JOptionPane.YES_NO_CANCEL_OPTION,
                    JOptionPane.WARNING_MESSAGE
            );

            if (option == JOptionPane.YES_OPTION) {
                boolean saved = saveFilesAction();
                if (!saved) {
                    return;
                }
            } else if (option == JOptionPane.CANCEL_OPTION || option == JOptionPane.CLOSED_OPTION) {
                return;
            }
        }

        editorPanel.setCodeText("");
        editorPanel.setConsoleTextArea("");
        editorPanel.setResult("");
        compiler = new Compiler();

        paintPanel(editorPanel);
        navText("Editor de código");
    }//GEN-LAST:event_newFileButtonActionPerformed

    private void openFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileButtonActionPerformed
        String currentText = editorPanel.getCodeText();

        if (currentText != null && !currentText.trim().isEmpty()) {
            int option = JOptionPane.showConfirmDialog(
                    this,
                    "El editor contiene texto. ¿Desea guardar los cambios antes de abrir un archivo?",
                    "Advertencia - Codex Latinus",
                    JOptionPane.YES_NO_CANCEL_OPTION,
                    JOptionPane.WARNING_MESSAGE
            );

            if (option == JOptionPane.YES_OPTION) {
                boolean saved = saveFilesAction();
                if (!saved) {
                    return;
                }
            } else if (option == JOptionPane.CANCEL_OPTION || option == JOptionPane.CLOSED_OPTION) {
                return;
            }
        }

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Seleccionar archivo de código (Latín o PigLatin)");

        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de Código (*.lat, *.pig)", "lat", "pig");
        fileChooser.setFileFilter(filter);

        int userSelection = fileChooser.showOpenDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToOpen = fileChooser.getSelectedFile();

            try {
                String contenido = new String(Files.readAllBytes(fileToOpen.toPath()), StandardCharsets.UTF_8);

                compiler = new Compiler();
                editorPanel.setResult("");

                paintPanel(editorPanel);
                navText("Editor de código / " + fileToOpen.getName());

                editorPanel.setCodeText(contenido);
                editorPanel.setConsoleTextArea("");

            } catch (java.io.IOException e) {
                JOptionPane.showMessageDialog(this,
                        "Error al leer el archivo: " + e.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_openFileButtonActionPerformed

    private void astButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_astButtonActionPerformed
        String dotContent = editorPanel.getLastDotCode();

        treePanel.renderGraph(dotContent);
        paintPanel(treePanel);
        navText("Árbol AST");
    }//GEN-LAST:event_astButtonActionPerformed

    private void symbolTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_symbolTableButtonActionPerformed
        SymbolTable table = editorPanel.getSymbolTable();
        List<Symbol> allSymbols = new ArrayList<>();

        if (table != null && table.getCurrentScope() != null) {
            collectSymbolsRecursive(table.getCurrentScope(), allSymbols);
        }

        SymbolTablePanel panel = new SymbolTablePanel();
        panel.loadSymbols(allSymbols);
        paintPanel(panel);
        navText("Tabla de símbolos");
    }//GEN-LAST:event_symbolTableButtonActionPerformed

    private void lexerErrorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lexerErrorButtonActionPerformed
        List<CompilationError> allErrors = editorPanel.getCompilationErrors();
        List<CompilationError> lexicalErrors = new ArrayList<>();

        if (allErrors != null) {
            lexicalErrors = allErrors.stream()
                    .filter(e -> "LEXICO".equalsIgnoreCase(e.getType()))
                    .collect(Collectors.toList());
        }

        ErrorTablePanel panel = new ErrorTablePanel();
        panel.loadErrors(lexicalErrors);
        paintPanel(panel);
        navText("Tabla de errores léxicos");
    }//GEN-LAST:event_lexerErrorButtonActionPerformed

    private void sintaxErrorButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sintaxErrorButton1ActionPerformed
        List<CompilationError> allErrors = editorPanel.getCompilationErrors();
        List<CompilationError> syntaxErrors = new ArrayList<>();

        if (allErrors != null) {
            syntaxErrors = allErrors.stream()
                    .filter(e -> "SINTACTICO".equalsIgnoreCase(e.getType()))
                    .collect(Collectors.toList());
        }

        ErrorTablePanel panel = new ErrorTablePanel();
        panel.loadErrors(syntaxErrors);
        paintPanel(panel);
        navText("Tabla de errores sintácticos");
    }//GEN-LAST:event_sintaxErrorButton1ActionPerformed

    private void semanticErrorButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semanticErrorButton1ActionPerformed
        List<CompilationError> allErrors = editorPanel.getCompilationErrors();
        List<CompilationError> semanticErrors = new ArrayList<>();

        if (allErrors != null) {
            semanticErrors = allErrors.stream()
                    .filter(e -> "SEMANTICO".equalsIgnoreCase(e.getType()))
                    .collect(Collectors.toList());
        }

        ErrorTablePanel panel = new ErrorTablePanel();
        panel.loadErrors(semanticErrors);
        paintPanel(panel);
        navText("Tabla errores semánticos");
    }//GEN-LAST:event_semanticErrorButton1ActionPerformed

    private void stackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stackButtonActionPerformed
        List<StackState> steps = editorPanel.getLastStackSteps();

        stackVisualizerPanel.loadStates(steps);
        paintPanel(stackVisualizerPanel);
        navText("Pila de procesos");
    }//GEN-LAST:event_stackButtonActionPerformed

    private void editTextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTextButtonActionPerformed
        paintPanel(editorPanel);
        navText("Editor de código");
    }//GEN-LAST:event_editTextButtonActionPerformed

    private void saveFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFileButtonActionPerformed
        saveFilesAction();
    }//GEN-LAST:event_saveFileButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton astButton;
    private javax.swing.JPanel contentPane;
    private javax.swing.JButton editTextButton;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton lexerErrorButton;
    private javax.swing.JLabel menuLabel;
    private javax.swing.JLabel navTextLabel;
    private javax.swing.JButton newFileButton;
    private javax.swing.JButton openFileButton;
    private javax.swing.JButton saveFileButton;
    private javax.swing.JButton semanticErrorButton1;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JButton sintaxErrorButton1;
    private javax.swing.JButton stackButton;
    private javax.swing.JButton symbolTableButton;
    // End of variables declaration//GEN-END:variables

    private void paintPanel(JPanel panel) {
        contentPane.removeAll();
        contentPane.add(panel);
        contentPane.revalidate();
        contentPane.repaint();
    }

    /**
     * Genera los estilos de los componentes.
     */
    private void initStyles() {
        menuLabel.putClientProperty("FlatLaf.style", "font: bold $h3.regular.font");
        menuLabel.setForeground(Color.white);

        navTextLabel.setOpaque(true);
        navTextLabel.setBackground(Color.BLACK);
        navTextLabel.setForeground(new Color(0, 255, 0));
        navTextLabel.setFont(new java.awt.Font("Monospaced", java.awt.Font.BOLD, 13));
        navTextLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));

        SwingUtilities.updateComponentTreeUI(this);
    }

    private void navText(String optionMenu) {
        navTextLabel.setText(navText + "/" + optionMenu);
    }

    private void initialPanel() {
        paintPanel(editorPanel);
        navText("Editor de código");
    }

    private void collectSymbolsRecursive(Scope scope, List<Symbol> list) {
        if (scope == null) {
            return;
        }

        if (scope.getSymbols() != null) {
            list.addAll(scope.getSymbols().values());
        }
    }

    private boolean saveFilesAction() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Seleccionar carpeta o indicar nombre para el proyecto");

        fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            File targetDirectory;

            String baseName = "proyecto";
            if (selectedFile.isDirectory()) {
                targetDirectory = selectedFile;
            } else {
                targetDirectory = selectedFile.getParentFile();
                String name = selectedFile.getName();
                int dotIndex = name.lastIndexOf('.');
                if (dotIndex > 0) {
                    baseName = name.substring(0, dotIndex);
                } else {
                    baseName = name;
                }
            }

            File projectFolder = new File(targetDirectory, baseName);
            if (!projectFolder.exists()) {
                boolean created = projectFolder.mkdirs();
                if (!created) {
                    JOptionPane.showMessageDialog(this,
                            "No se pudo crear la carpeta para los archivos.",
                            "Error de almacenamiento",
                            JOptionPane.ERROR_MESSAGE);
                    return false;
                }
            }

            File latFile = new File(projectFolder, baseName + ".lat");
            File pigFile = new File(projectFolder, baseName + ".pig");

            try {
                String codeContent = editorPanel.getCodeText();
                try (FileWriter writer = new FileWriter(latFile, StandardCharsets.UTF_8)) {
                    writer.write(codeContent);
                }

                compiler.parseCode(codeContent);
                String pigContent = editorPanel.getResult() != null ? editorPanel.getResult() : "";

                try (FileWriter writerPig = new FileWriter(pigFile, StandardCharsets.UTF_8)) {
                    writerPig.write(pigContent);
                }

                JOptionPane.showMessageDialog(this,
                        "Carpeta y archivos creados exitosamente en:\n" + projectFolder.getAbsolutePath()
                        + "\n- " + latFile.getName()
                        + "\n- " + pigFile.getName(),
                        "Guardado Exitoso",
                        JOptionPane.INFORMATION_MESSAGE);
                return true;

            } catch (IOException e) {
                JOptionPane.showMessageDialog(this,
                        "Error al guardar los archivos: " + e.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }
        return false;
    }
}
