package com.compi.frontend;

import java.awt.Color;
import java.awt.Dimension;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author michael
 */
public class MainWindow extends JFrame {

    private static final String navText = "Contacto 3xtrat3rr3str3D";
    private final EditorPanel editorPanel = new EditorPanel();
   // private Compiler compiler = new Compiler();
    private final StackVisualizerPanel stackVisualizerPanel = new StackVisualizerPanel();
    private JPanel contentArea;
    private File currentFile;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        setTitle("Contacto 3xtrat3rr3str3D");
        setMinimumSize(new Dimension(685, 461));
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initContentLayout();
        initStyles();
        navText("");
        initialPanel();
    }

    /**
     * Arma el área de contenido con el árbol de archivos a la izquierda y el
     * panel activo (editor, AST, tablas, pila) a la derecha.
     */
    private void initContentLayout() {
        contentArea = new JPanel(new java.awt.BorderLayout());
        contentArea.setBackground(new Color(240, 240, 240));

        contentPane.removeAll();
        contentPane.setLayout(new java.awt.BorderLayout());
        contentPane.add(contentArea, java.awt.BorderLayout.CENTER);
        contentPane.revalidate();
        contentPane.repaint();
    }

    /**
     * Carga el archivo seleccionado en el árbol de archivos.
     */
    private void loadFileFromTree(File file) {
        try {
            String contenido = new String(Files.readAllBytes(file.toPath()), StandardCharsets.UTF_8);
            currentFile = file;
            editorPanel.setResult("");
            editorPanel.setCodeText(contenido);
            editorPanel.setConsoleTextArea("");
            editorPanel.setC3DText("");
            paintPanel(editorPanel);
            navText("Editor de código / ");
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this,
                    "Error al leer el archivo: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        sidebarPanel = new javax.swing.JPanel();
        openFileButton = new javax.swing.JButton();
        saveFileButton = new javax.swing.JButton();
        astButton = new javax.swing.JButton();
        symbolTableButton = new javax.swing.JButton();
        stackButton = new javax.swing.JButton();
        newFileButton = new javax.swing.JButton();
        lexerErrorButton = new javax.swing.JButton();
        optionSelectedLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        contentPane = new javax.swing.JPanel();
        fileTreePanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidebarPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        openFileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/open-file.png"))); // NOI18N
        openFileButton.setBorder(new javax.swing.border.MatteBorder(null));
        openFileButton.setBorderPainted(false);
        openFileButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        openFileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                openFileButtonMouseEntered(evt);
            }
        });
        openFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileButtonActionPerformed(evt);
            }
        });
        sidebarPanel.add(openFileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 30, 30));

        saveFileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/save-file.png"))); // NOI18N
        saveFileButton.setBorder(new javax.swing.border.MatteBorder(null));
        saveFileButton.setBorderPainted(false);
        saveFileButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveFileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveFileButtonMouseEntered(evt);
            }
        });
        saveFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveFileButtonActionPerformed(evt);
            }
        });
        sidebarPanel.add(saveFileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 30, 30));

        astButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ast.png"))); // NOI18N
        astButton.setBorder(new javax.swing.border.MatteBorder(null));
        astButton.setBorderPainted(false);
        astButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        astButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                astButtonMouseEntered(evt);
            }
        });
        astButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                astButtonActionPerformed(evt);
            }
        });
        sidebarPanel.add(astButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 30, 30));

        symbolTableButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/symbol-table.png"))); // NOI18N
        symbolTableButton.setBorder(new javax.swing.border.MatteBorder(null));
        symbolTableButton.setBorderPainted(false);
        symbolTableButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        symbolTableButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                symbolTableButtonMouseEntered(evt);
            }
        });
        symbolTableButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                symbolTableButtonActionPerformed(evt);
            }
        });
        sidebarPanel.add(symbolTableButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 30, 30));

        stackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/stack.png"))); // NOI18N
        stackButton.setBorder(new javax.swing.border.MatteBorder(null));
        stackButton.setBorderPainted(false);
        stackButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        stackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stackButtonMouseEntered(evt);
            }
        });
        stackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stackButtonActionPerformed(evt);
            }
        });
        sidebarPanel.add(stackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 30, 30));

        newFileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/new-file.png"))); // NOI18N
        newFileButton.setBorder(new javax.swing.border.MatteBorder(null));
        newFileButton.setBorderPainted(false);
        newFileButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        newFileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newFileButtonMouseEntered(evt);
            }
        });
        newFileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFileButtonActionPerformed(evt);
            }
        });
        sidebarPanel.add(newFileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        lexerErrorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/error-table.png"))); // NOI18N
        lexerErrorButton.setBorder(new javax.swing.border.MatteBorder(null));
        lexerErrorButton.setBorderPainted(false);
        lexerErrorButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lexerErrorButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lexerErrorButtonMouseEntered(evt);
            }
        });
        lexerErrorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lexerErrorButtonActionPerformed(evt);
            }
        });
        sidebarPanel.add(lexerErrorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 30, 30));

        optionSelectedLabel.setText("jLabel1");
        sidebarPanel.add(optionSelectedLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 710, 30));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        sidebarPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 10, 30));

        contentPane.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout fileTreePanelLayout = new javax.swing.GroupLayout(fileTreePanel);
        fileTreePanel.setLayout(fileTreePanelLayout);
        fileTreePanelLayout.setHorizontalGroup(
            fileTreePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
        );
        fileTreePanelLayout.setVerticalGroup(
            fileTreePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(4, 4, 4))
            .addComponent(fileTreePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidebarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(contentPane, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fileTreePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(2, 2, 2))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFileButtonActionPerformed
        String currentText = editorPanel.getCodeText();

        if (currentText != null && !currentText.trim().isEmpty()) {
            int option = JOptionPane.showConfirmDialog(
                    this,
                    "El editor contiene texto. ¿Desea guardar los cambios antes de crear un nuevo archivo?",
                    "Advertencia - Codex Latinus",
                    JOptionPane.YES_NO_CANCEL_OPTION,
                    JOptionPane.WARNING_MESSAGE
            );

            if (option == JOptionPane.YES_OPTION) {
                boolean saved = saveFilesAction();
                if (!saved) {
                    return;
                }
            } else if (option == JOptionPane.CANCEL_OPTION || option == JOptionPane.CLOSED_OPTION) {
                return;
            }
        }

        editorPanel.setCodeText("");
        editorPanel.setConsoleTextArea("");
        editorPanel.setResult("");
        editorPanel.setC3DText("");
        currentFile = null;
        //compiler = new Compiler();

        paintPanel(editorPanel);
        navText("Editor de código");
    }//GEN-LAST:event_newFileButtonActionPerformed

    private void openFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileButtonActionPerformed
        String currentText = editorPanel.getCodeText();

        if (currentText != null && !currentText.trim().isEmpty()) {
            int option = JOptionPane.showConfirmDialog(
                    this,
                    "El editor contiene texto. ¿Desea guardar los cambios antes de abrir un archivo?",
                    "Advertencia - Codex Latinus",
                    JOptionPane.YES_NO_CANCEL_OPTION,
                    JOptionPane.WARNING_MESSAGE
            );

            if (option == JOptionPane.YES_OPTION) {
                boolean saved = saveFilesAction();
                if (!saved) {
                    return;
                }
            } else if (option == JOptionPane.CANCEL_OPTION || option == JOptionPane.CLOSED_OPTION) {
                return;
            }
        }

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Seleccionar archivo de código (Latín, PigLatin, Y, Zetariano)");

        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "Archivos de Código (*.lat, *.pig, *.y, *.z)", "lat", "pig", "y", "z");
        fileChooser.setFileFilter(filter);

        int userSelection = fileChooser.showOpenDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToOpen = fileChooser.getSelectedFile();

            try {
                String contenido = new String(Files.readAllBytes(fileToOpen.toPath()), StandardCharsets.UTF_8);

                //compiler = new Compiler();
                editorPanel.setResult("");

                paintPanel(editorPanel);
                navText("Editor de código / " + fileToOpen.getName());

                editorPanel.setCodeText(contenido);
                editorPanel.setConsoleTextArea("");
                editorPanel.setC3DText("");

                currentFile = fileToOpen;

            } catch (IOException e) {
                JOptionPane.showMessageDialog(this,
                        "Error al leer el archivo: " + e.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_openFileButtonActionPerformed

    private void astButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_astButtonActionPerformed
        /*String dotContent = editorPanel.getLastDotCode();

        treePanel.renderGraph(dotContent);
        paintPanel(treePanel);
        navText("Árbol AST");*/
    }//GEN-LAST:event_astButtonActionPerformed

    private void symbolTableButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_symbolTableButtonActionPerformed
        /*SymbolTable table = editorPanel.getSymbolTable();
        List<Symbol> allSymbols = new ArrayList<>();

        if (table != null && table.getCurrentScope() != null) {
            collectSymbolsRecursive(table.getCurrentScope(), allSymbols);
        }

        SymbolTablePanel panel = new SymbolTablePanel();
        panel.loadSymbols(allSymbols);
        paintPanel(panel);
        navText("Tabla de símbolos");*/
    }//GEN-LAST:event_symbolTableButtonActionPerformed

    private void lexerErrorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lexerErrorButtonActionPerformed
       /* List<CompilationError> allErrors = editorPanel.getCompilationErrors();
        List<CompilationError> lexicalErrors = new ArrayList<>();

        if (allErrors != null) {
            lexicalErrors = allErrors.stream()
                    .filter(e -> "LEXICO".equalsIgnoreCase(e.getType()))
                    .collect(Collectors.toList());
        }

        ErrorTablePanel panel = new ErrorTablePanel();
        panel.loadErrors(lexicalErrors);
        paintPanel(panel);
        navText("Tabla de errores léxicos");*/
    }//GEN-LAST:event_lexerErrorButtonActionPerformed

    private void stackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stackButtonActionPerformed
       /* List<StackState> steps = editorPanel.getLastStackSteps();

        stackVisualizerPanel.loadStates(steps);
        paintPanel(stackVisualizerPanel);
        navText("Pila de procesos");*/
    }//GEN-LAST:event_stackButtonActionPerformed

    private void saveFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveFileButtonActionPerformed
        saveFilesAction();
    }//GEN-LAST:event_saveFileButtonActionPerformed

    private void newFileButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newFileButtonMouseEntered
        this.optionSelectedLabel.setText("Nuevo archivo");
    }//GEN-LAST:event_newFileButtonMouseEntered

    private void openFileButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openFileButtonMouseEntered
        this.optionSelectedLabel.setText("Abrir archivo");
    }//GEN-LAST:event_openFileButtonMouseEntered

    private void saveFileButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveFileButtonMouseEntered
        this.optionSelectedLabel.setText("Guardar archivo");
    }//GEN-LAST:event_saveFileButtonMouseEntered

    private void symbolTableButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_symbolTableButtonMouseEntered
        this.optionSelectedLabel.setText("Tabla de Símbolos");
    }//GEN-LAST:event_symbolTableButtonMouseEntered

    private void astButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_astButtonMouseEntered
        this.optionSelectedLabel.setText("AST");
    }//GEN-LAST:event_astButtonMouseEntered

    private void stackButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stackButtonMouseEntered
        this.optionSelectedLabel.setText("Pila de Procesos");
    }//GEN-LAST:event_stackButtonMouseEntered

    private void lexerErrorButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lexerErrorButtonMouseEntered
        this.optionSelectedLabel.setText("Tabla de Errores");
    }//GEN-LAST:event_lexerErrorButtonMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton astButton;
    private javax.swing.JPanel contentPane;
    private javax.swing.JPanel fileTreePanel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton lexerErrorButton;
    private javax.swing.JButton newFileButton;
    private javax.swing.JButton openFileButton;
    private javax.swing.JLabel optionSelectedLabel;
    private javax.swing.JButton saveFileButton;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JButton stackButton;
    private javax.swing.JButton symbolTableButton;
    // End of variables declaration//GEN-END:variables

    private void paintPanel(JPanel panel) {
        JPanel target = (contentArea != null) ? contentArea : contentPane;
        target.removeAll();
        target.add(panel, java.awt.BorderLayout.CENTER);
        target.revalidate();
        target.repaint();
    }

    /**
     * Genera los estilos de los componentes.
     */
    private void initStyles() {

        optionSelectedLabel.setOpaque(true);
        optionSelectedLabel.setBackground(Color.BLACK);
        optionSelectedLabel.setForeground(new Color(0, 255, 0));
        optionSelectedLabel.setFont(new java.awt.Font("Monospaced", java.awt.Font.BOLD, 13));
        optionSelectedLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));

        SwingUtilities.updateComponentTreeUI(this);
    }

    private void navText(String optionMenu) {
        optionSelectedLabel.setText(navText + "/" + optionMenu);
    }

    private void initialPanel() {
        paintPanel(editorPanel);
        navText("Editor de código");
    }


    private boolean saveFilesAction() {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Seleccionar carpeta o indicar nombre para el proyecto");

        fileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            File targetDirectory;

            String baseName = "proyecto";
            if (selectedFile.isDirectory()) {
                targetDirectory = selectedFile;
            } else {
                targetDirectory = selectedFile.getParentFile();
                String name = selectedFile.getName();
                int dotIndex = name.lastIndexOf('.');
                if (dotIndex > 0) {
                    baseName = name.substring(0, dotIndex);
                } else {
                    baseName = name;
                }
            }

            File projectFolder = new File(targetDirectory, baseName);
            if (!projectFolder.exists()) {
                boolean created = projectFolder.mkdirs();
                if (!created) {
                    JOptionPane.showMessageDialog(this,
                            "No se pudo crear la carpeta para los archivos.",
                            "Error de almacenamiento",
                            JOptionPane.ERROR_MESSAGE);
                    return false;
                }
            }

            File latFile = new File(projectFolder, baseName + ".lat");
            File pigFile = new File(projectFolder, baseName + ".pig");

            try {
                String codeContent = editorPanel.getCodeText();
                try (FileWriter writer = new FileWriter(latFile, StandardCharsets.UTF_8)) {
                    writer.write(codeContent);
                }

                //compiler.parseCode(codeContent);
                String pigContent = editorPanel.getResult() != null ? editorPanel.getResult() : "";

                try (FileWriter writerPig = new FileWriter(pigFile, StandardCharsets.UTF_8)) {
                    writerPig.write(pigContent);
                }

                // Registrar los archivos guardados en el árbol de archivos

                currentFile = latFile;

                JOptionPane.showMessageDialog(this,
                        "Carpeta y archivos creados exitosamente en:\n" + projectFolder.getAbsolutePath()
                        + "\n- " + latFile.getName()
                        + "\n- " + pigFile.getName(),
                        "Guardado Exitoso",
                        JOptionPane.INFORMATION_MESSAGE);
                return true;

            } catch (IOException e) {
                JOptionPane.showMessageDialog(this,
                        "Error al guardar los archivos: " + e.getMessage(),
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                return false;
            }
        }
        return false;
    }
}
