package com.compi.frontend;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.event.MouseWheelEvent;
import java.awt.event.MouseWheelListener;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingConstants;

/**
 *
 * @author michael
 */
public class ParserTreePanel extends JPanel {

    private ZoomableImagePanel imagePanel;
    private JScrollPane scrollPane;
    private Image originalImage = null;
    private double zoomFactor = 1.0;
    private JLabel messageLabel;

    /**
     * Creates new form ParserTree
     */
    public ParserTreePanel() {
        initComponents();
        initCustomComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    private void initCustomComponents() {
        this.setLayout(new BorderLayout());

        messageLabel = new JLabel("No hay árbol AST generado aún.", SwingConstants.CENTER);

        // Panel personalizado que escala instantáneamente mediante Graphics2D
        imagePanel = new ZoomableImagePanel();
        imagePanel.setLayout(new BorderLayout());
        imagePanel.add(messageLabel, BorderLayout.CENTER);

        scrollPane = new JScrollPane(imagePanel);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED);

        // Listener optimizado para el Zoom (Ctrl + Scroll)
        scrollPane.addMouseWheelListener(new MouseWheelListener() {
            @Override
            public void mouseWheelMoved(MouseWheelEvent e) {
                if (originalImage == null) {
                    return;
                }

                if (e.isControlDown()) {
                    e.consume();

                    double oldFactor = zoomFactor;
                    if (e.getPreciseWheelRotation() < 0) {
                        zoomFactor *= 1.1; // Acercar
                    } else {
                        zoomFactor /= 1.1; // Alejar
                    }

                    // Limitar zoom entre 10% y 500%
                    zoomFactor = Math.max(0.1, Math.min(5.0, zoomFactor));

                    // Solo repintar si el zoom cambió realmente
                    if (oldFactor != zoomFactor) {
                        imagePanel.revalidate();
                        imagePanel.repaint();
                    }
                }
            }
        });

        this.add(scrollPane, BorderLayout.CENTER);
    }

    /**
     * Panel interno encargado de renderizar la imagen con escala vectorial
     * fluida.
     */
    private class ZoomableImagePanel extends JPanel {

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            if (originalImage != null) {
                Graphics2D g2d = (Graphics2D) g.create();
                g2d.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
                g2d.scale(zoomFactor, zoomFactor);
                g2d.drawImage(originalImage, 0, 0, this);
                g2d.dispose();
            }
        }

        @Override
        public Dimension getPreferredSize() {
            if (originalImage == null) {
                return super.getPreferredSize();
            }
            int width = (int) (originalImage.getWidth(null) * zoomFactor);
            int height = (int) (originalImage.getHeight(null) * zoomFactor);
            return new Dimension(width, height);
        }
    }

    /**
     * Recibe el código DOT de Graphviz, genera la imagen y la muestra en el
     * panel.
     *
     * @param dotCode Contenido en formato DOT del AST.
     */
    public void renderGraph(String dotCode) {
        if (dotCode == null || dotCode.trim().isEmpty()) {
            originalImage = null;
            zoomFactor = 1.0;
            messageLabel.setText("No se generó el árbol debido a errores.\nVerifique las tablas de errores para más detalles.");
            messageLabel.setVisible(true);
            imagePanel.revalidate();
            imagePanel.repaint();
            return;
        }

        try {
            File tempDot = File.createTempFile("ast_graph", ".dot");
            File tempImg = File.createTempFile("ast_graph", ".png");
            tempImg.deleteOnExit();

            try (FileWriter writer = new FileWriter(tempDot)) {
                writer.write(dotCode);
            }

            ProcessBuilder processBuilder = new ProcessBuilder("dot", "-Tpng", tempDot.getAbsolutePath(), "-o", tempImg.getAbsolutePath());
            Process process = processBuilder.start();
            int exitCode = process.waitFor();

            if (exitCode == 0) {
                ImageIcon icon = new ImageIcon(tempImg.getAbsolutePath());
                originalImage = icon.getImage();
                zoomFactor = 1.0; // Resetear zoom al generar un nuevo árbol
                messageLabel.setVisible(false);
                imagePanel.revalidate();
                imagePanel.repaint();
            } else {
                originalImage = null;
                zoomFactor = 1.0;
                messageLabel.setText("Error al compilar Graphviz (Asegúrate de tenerlo instalado).");
                messageLabel.setVisible(true);
                imagePanel.revalidate();
                imagePanel.repaint();
                JOptionPane.showMessageDialog(this,
                        "Graphviz devolvió un código de salida no exitoso. ¿Está instalado 'dot' en tu PATH?",
                        "Error de Graphviz",
                        JOptionPane.ERROR_MESSAGE);
            }

            tempDot.delete();

        } catch (IOException | InterruptedException e) {
            originalImage = null;
            zoomFactor = 1.0;
            messageLabel.setText("Excepción al generar la imagen del AST.");
            messageLabel.setVisible(true);
            imagePanel.revalidate();
            imagePanel.repaint();
            JOptionPane.showMessageDialog(this,
                    "Error al procesar Graphviz: " + e.getMessage() + "\nVerifica que Graphviz esté instalado en el sistema.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            if (Thread.currentThread().isInterrupted()) {
                Thread.currentThread().interrupt();
            }
        }
    }
}
