package com.compi.frontend;

import com.compi.backend.runtime.StackState;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSlider;
import javax.swing.JSplitPane;
import javax.swing.JTextArea;
import javax.swing.SwingConstants;

/**
 * Visualizador de la pila de procesos de la maquina abstracta.
 *
 * Muestra un control deslizante para recorrer los pasos de la simulacion y un
 * dibujo de la pila en ese instante, junto con la instruccion que la produce.
 */
public class StackVisualizerPanel extends JPanel {

    private JPanel stackDrawPanel;
    private JTextArea logTextArea;
    private JSlider stepSlider;
    private JLabel stepLabel;
    private JSplitPane splitPane;

    private List<StackState> states = new ArrayList<>();
    private int currentStep = 0;

    /**
     * Creates new form StackVisualizerPanel
     */
    public StackVisualizerPanel() {
        initComponents();
        initCustomComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private void initCustomComponents() {
        setLayout(new BorderLayout());

        stackDrawPanel = new StackPanel();
        stackDrawPanel.setBackground(UiTheme.toolWindowBg());
        stackDrawPanel.setPreferredSize(new Dimension(0, 260));
        stackDrawPanel.setBorder(UiTheme.pad(8, 8, 8, 8));

        logTextArea = new JTextArea();
        logTextArea.setEditable(false);
        logTextArea.setFont(UiTheme.mono(11));
        logTextArea.setBackground(UiTheme.toolWindowBg());
        logTextArea.setForeground(UiTheme.dim());
        logTextArea.setBorder(UiTheme.pad(4, 8, 4, 8));
        logTextArea.setVisible(false);

        splitPane = new JSplitPane(JSplitPane.VERTICAL_SPLIT, stackDrawPanel,
                new JScrollPane(logTextArea));
        splitPane.setResizeWeight(0.72);
        splitPane.setDividerLocation(260);
        splitPane.setBorder(BorderFactory.createEmptyBorder());
        splitPane.setContinuousLayout(true);
        splitPane.setOneTouchExpandable(true);

        stepSlider = new JSlider(0, 0, 0);
        stepSlider.setEnabled(false);
        stepSlider.setBackground(UiTheme.toolWindowBg());
        stepSlider.addChangeListener(e -> {
            currentStep = stepSlider.getValue();
            updateStepLabel();
            stackDrawPanel.repaint();
        });

        stepLabel = new JLabel("Paso 0 / 0", SwingConstants.CENTER);
        stepLabel.setFont(UiTheme.sans(11));
        stepLabel.setForeground(UiTheme.dim());

        JButton first = navButton(IdeIcons.zoomOut(), "Primer paso", 0);
        JButton prev = navButton(IdeIcons.chevronDown(), "Paso anterior", -1);
        JButton next = navButton(IdeIcons.chevronDown(), "Paso siguiente", 1);
        JButton last = navButton(IdeIcons.zoomIn(), "Último paso", Integer.MAX_VALUE);
        JButton log = new JButton("Bitácora");
        log.setFocusable(false);
        log.setFont(UiTheme.sans(12));
        log.addActionListener(e -> {
            logTextArea.setVisible(!logTextArea.isVisible());
            splitPane.setDividerLocation(logTextArea.isVisible() ? 200 : 260);
        });

        JPanel controls = new JPanel(new BorderLayout());
        JPanel nav = new JPanel(new FlowLayout(FlowLayout.LEFT, 2, 0));
        nav.setOpaque(false);
        nav.add(first);
        nav.add(prev);
        nav.add(next);
        nav.add(last);
        nav.add(stepLabel);

        JPanel right = new JPanel(new FlowLayout(FlowLayout.RIGHT, 2, 0));
        right.setOpaque(false);
        right.add(log);

        controls.setBorder(UiTheme.pad(6, 6, 4, 8));
        controls.add(nav, BorderLayout.WEST);
        controls.add(right, BorderLayout.EAST);

        JPanel south = new JPanel(new BorderLayout());
        south.setOpaque(false);
        south.add(controls, BorderLayout.NORTH);
        south.add(stepSlider, BorderLayout.CENTER);

        add(controls, BorderLayout.NORTH);
        add(splitPane, BorderLayout.CENTER);
        add(stepSlider, BorderLayout.SOUTH);
    }

    private JButton navButton(javax.swing.Icon icon, String tooltip, int delta) {
        JButton b = new JButton(icon);
        b.setToolTipText(tooltip);
        b.setFocusable(false);
        b.setBorderPainted(false);
        b.setContentAreaFilled(false);
        b.setPreferredSize(new Dimension(24, 24));
        UiTheme.asButton(b);
        b.addActionListener(e -> {
            if (delta == Integer.MAX_VALUE) {
                currentStep = states.size() - 1;
            } else {
                currentStep += delta;
            }
            currentStep = Math.max(0, Math.min(states.size() - 1, currentStep));
            stepSlider.setValue(currentStep);
            updateStepLabel();
            stackDrawPanel.repaint();
        });
        return b;
    }

    // ====================== API ======================

    /**
     * Carga los estados de la pila y muestra el ultimo.
     */
    public void loadStates(List<StackState> newStates) {
        states = newStates == null ? new ArrayList<>() : new ArrayList<>(newStates);
        stepSlider.setEnabled(states.size() > 1);
        stepSlider.setMaximum(Math.max(0, states.size() - 1));
        currentStep = states.size() - 1;
        stepSlider.setValue(currentStep);
        updateStepLabel();
        stackDrawPanel.repaint();
        rebuildLog();
    }

    private void rebuildLog() {
        StringBuilder sb = new StringBuilder();
        for (StackState s : states) {
            sb.append(s).append('\n');
        }
        logTextArea.setText(sb.toString());
        logTextArea.setCaretPosition(0);
    }

    private void updateStepLabel() {
        stepLabel.setText("Paso " + (states.isEmpty() ? 0 : currentStep + 1) + " / " + states.size());
    }

    public int getStateCount() {
        return states.size();
    }

    public int getCurrentStep() {
        return currentStep;
    }

    public void clear() {
        loadStates(null);
    }

    /** Estado visible ahora mismo. */
    public StackState getCurrentState() {
        if (states.isEmpty()) {
            return null;
        }
        return states.get(Math.max(0, Math.min(states.size() - 1, currentStep)));
    }

    // ====================== Dibujo de la pila ======================

    /** Dibuja las celdas de la pila, con la cima arriba. */
    private class StackPanel extends JPanel {

        private static final int CELL_HEIGHT = 26;
        private static final int GAP = 4;

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Graphics2D g2 = (Graphics2D) g.create();
            g2.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING,
                    RenderingHints.VALUE_TEXT_ANTIALIAS_ON);
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
                    RenderingHints.VALUE_ANTIALIAS_ON);

            StackState state = getCurrentState();
            g2.setFont(UiTheme.mono(12));

            if (state == null) {
                g2.setColor(UiTheme.dim());
                g2.drawString("Sin datos de pila. Compila un archivo para ver la simulación.",
                        12, 24);
                g2.dispose();
                return;
            }

            g2.setColor(UiTheme.dim());
            g2.drawString("Instrucción: " + state.getC3dInstruction(), 8, 16);

            if (state.getStackElements().isEmpty()) {
                g2.setColor(UiTheme.dim());
                g2.drawString("Pila vacía", 12, 44);
                g2.dispose();
                return;
            }

            List<String> elements = state.getStackElements();
            int top = 32;
            FontMetrics fm = g2.getFontMetrics();
            int topIndex = elements.size() - 1;

            for (int row = 0; row < elements.size(); row++) {
                int i = topIndex - row;
                int y = top + row * (CELL_HEIGHT + GAP);
                boolean isTop = row == 0;

                g2.setColor(isTop ? UiTheme.accent().darker() : UiTheme.color("Table.selectionBackground",
                        new Color(0x313335)));
                g2.fillRoundRect(8, y, Math.max(80, getWidth() - 16), CELL_HEIGHT, 6, 6);

                g2.setColor(isTop ? Color.WHITE : UiTheme.fg());
                g2.drawString(elements.get(i), 16, y + fm.getAscent() + 4);
            }
            g2.dispose();
        }

        @Override
        public Dimension getPreferredSize() {
            return new Dimension(320, 300);
        }
    }
}
