package com.compi.frontend;

import codex_latinus.backend.stack.StackState;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JTextArea;

/**
 *
 * @author michael
 */
public class StackVisualizerPanel extends javax.swing.JPanel {

    private List<StackState> stackStates = new ArrayList<>();
    private JPanel stackDrawPanel;
    private JTextArea logTextArea;
    private JSplitPane splitPane;

    /**
     * Creates new form StackVisualizerPanel
     */
    public StackVisualizerPanel() {
        initComponents();
        initCustomComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private void initCustomComponents() {
        this.setLayout(new BorderLayout());

        stackDrawPanel = new JPanel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                drawAllSteps(g);
            }
        };
        stackDrawPanel.setBackground(Color.WHITE);

        JScrollPane stackScrollPane = new JScrollPane(stackDrawPanel,
                JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,
                JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);

        JPanel topContainer = new JPanel(new BorderLayout());
        JLabel lblTitle = new JLabel("  Secuencia de Estados de la Pila (Historial Completo)");
        lblTitle.setFont(new Font("SansSerif", Font.BOLD, 12));
        topContainer.add(lblTitle, BorderLayout.NORTH);
        topContainer.add(stackScrollPane, BorderLayout.CENTER);

        // 2. Panel Inferior (Consola de Logs detallada)
        logTextArea = new JTextArea();
        logTextArea.setEditable(false);
        logTextArea.setFont(new Font("Monospaced", Font.PLAIN, 12));
        logTextArea.setBackground(new Color(30, 30, 30));
        logTextArea.setForeground(new Color(220, 220, 220));
        JScrollPane logScrollPane = new JScrollPane(logTextArea);

        JPanel bottomContainer = new JPanel(new BorderLayout());
        JLabel lblLogTitle = new JLabel("  Consola de Logs / Operaciones:");
        lblLogTitle.setFont(new Font("SansSerif", Font.BOLD, 11));
        bottomContainer.add(lblLogTitle, BorderLayout.NORTH);
        bottomContainer.add(logScrollPane, BorderLayout.CENTER);

        splitPane = new JSplitPane(JSplitPane.VERTICAL_SPLIT, topContainer, bottomContainer);
        splitPane.setResizeWeight(0.75);
        splitPane.setDividerLocation(350);

        this.add(splitPane, BorderLayout.CENTER);
    }

    public void loadStates(List<StackState> states) {
        this.stackStates = states != null ? states : new ArrayList<>();

        int totalSteps = stackStates.isEmpty() ? 1 : stackStates.size();

        int maxDepth = 1;
        for (StackState st : stackStates) {
            if (st.getStackElements() != null) {
                maxDepth = Math.max(maxDepth, st.getStackElements().size());
            }
        }

        int colWidth = 115;
        int boxHeight = 26;
        int spacing = 4;

        int containerHeight = Math.max(280, maxDepth * (boxHeight + spacing) + 50);

        int panelWidth = Math.max(800, totalSteps * colWidth + 40);
        int panelHeight = containerHeight + 70; // Margen para numeración y badges

        stackDrawPanel.setPreferredSize(new Dimension(panelWidth, panelHeight));

        updateLogs();
        stackDrawPanel.revalidate();
        stackDrawPanel.repaint();
    }

    private void updateLogs() {
        StringBuilder logs = new StringBuilder();
        for (int i = 0; i < stackStates.size(); i++) {
            StackState st = stackStates.get(i);
            logs.append("[Paso ").append(i + 1).append("] ").append(st.getOperation()).append("\n");
        }
        logTextArea.setText(logs.toString());
    }

    private void drawAllSteps(Graphics g) {
        if (stackStates.isEmpty()) {
            Graphics2D g2d = (Graphics2D) g;
            g2d.setColor(Color.GRAY);
            g2d.setFont(new Font("SansSerif", Font.ITALIC, 14));
            g2d.drawString("No hay estados de pila para mostrar. Ejecute el análisis de código.", 30, 50);
            return;
        }

        Graphics2D g2d = (Graphics2D) g;
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        int startX = 20;
        int colWidth = 115;
        int boxHeight = 26;
        int spacing = 4;

        int maxDepth = 1;
        for (StackState st : stackStates) {
            if (st.getStackElements() != null) {
                maxDepth = Math.max(maxDepth, st.getStackElements().size());
            }
        }
        int containerHeight = Math.max(240, maxDepth * (boxHeight + spacing) + 30);

        for (int i = 0; i < stackStates.size(); i++) {
            StackState state = stackStates.get(i);
            List<String> elements = state.getStackElements();

            g2d.setColor(Color.DARK_GRAY);
            g2d.setFont(new Font("SansSerif", Font.BOLD, 12));
            String stepNumStr = String.valueOf(i + 1);
            int numWidth = g2d.getFontMetrics().stringWidth(stepNumStr);
            g2d.drawString(stepNumStr, startX + (colWidth - numWidth) / 2, 20);

            g2d.setColor(new Color(254, 243, 199));
            g2d.fillRoundRect(startX, 28, colWidth - 10, containerHeight, 10, 10);
            g2d.setColor(new Color(217, 119, 6));
            g2d.drawRoundRect(startX, 28, colWidth - 10, containerHeight, 10, 10);

            int currentY = 36;

            if (elements.isEmpty()) {
                g2d.setColor(Color.GRAY);
                g2d.setFont(new Font("SansSerif", Font.ITALIC, 11));
                String emptyText = "Pila Vacía";
                int emptyWidth = g2d.getFontMetrics().stringWidth(emptyText);
                g2d.drawString(emptyText, startX + (colWidth - 10 - emptyWidth) / 2, currentY + 30);
            } else {
                for (int j = elements.size() - 1; j >= 0; j--) {
                    String el = elements.get(j);

                    if (j == elements.size() - 1) {
                        g2d.setColor(new Color(191, 219, 254));
                    } else {
                        g2d.setColor(new Color(254, 202, 202));
                    }

                    g2d.fillRoundRect(startX + 6, currentY, colWidth - 22, boxHeight, 5, 5);
                    g2d.setColor(Color.GRAY);
                    g2d.drawRoundRect(startX + 6, currentY, colWidth - 22, boxHeight, 5, 5);

                    Font boxFont = new Font("SansSerif", Font.BOLD, 10);
                    g2d.setFont(boxFont);
                    FontMetrics fm = g2d.getFontMetrics();

                    String displayEl = el;
                    while (fm.stringWidth(displayEl) > colWidth - 28 && displayEl.length() > 3) {
                        displayEl = displayEl.substring(0, displayEl.length() - 1);
                    }
                    if (!displayEl.equals(el)) {
                        displayEl += "..";
                    }

                    g2d.setColor(Color.BLACK);
                    int textX = startX + 6 + ((colWidth - 22 - fm.stringWidth(displayEl)) / 2);
                    int textY = currentY + ((boxHeight - fm.getHeight()) / 2) + fm.getAscent();
                    g2d.drawString(displayEl, textX, textY);

                    currentY += boxHeight + spacing;
                }
            }

            int badgeY = 32 + containerHeight + 6;
            String operation = state.getOperation() != null ? state.getOperation() : "";
            g2d.setColor(new Color(187, 247, 208));
            g2d.fillRoundRect(startX + 2, badgeY, colWidth - 14, 24, 6, 6);
            g2d.setColor(new Color(22, 101, 52));
            g2d.drawRoundRect(startX + 2, badgeY, colWidth - 14, 24, 6, 6);

            g2d.setColor(new Color(20, 83, 45));
            g2d.setFont(new Font("SansSerif", Font.PLAIN, 9));
            FontMetrics fmOp = g2d.getFontMetrics();

            if (fmOp.stringWidth(operation) > colWidth - 18) {
                while (operation.length() > 3 && fmOp.stringWidth(operation + "...") > colWidth - 18) {
                    operation = operation.substring(0, operation.length() - 1);
                }
                operation += "...";
            }
            int opX = startX + 2 + ((colWidth - 14 - fmOp.stringWidth(operation)) / 2);
            int opY = badgeY + ((24 - fmOp.getHeight()) / 2) + fmOp.getAscent();
            g2d.drawString(operation, opX, opY);

            startX += colWidth;
        }
    }
}
