package com.compi.frontend;

import com.compi.backend.parser.AccionPila;
import com.compi.backend.parser.ParseStep;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import java.awt.RenderingHints;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JSplitPane;
import javax.swing.JTextArea;
import javax.swing.JViewport;
import javax.swing.SwingConstants;

/**
 * Visualizador de la pila del parser.
 *
 * <p>Se divide en dos partes. La parte grafica dibuja una columna por cada paso
 * del trazo: el numero de paso, si la accion fue un desplazamiento (shift) o una
 * reduccion (reduce) y el contenido de la pila en ese instante, con la cima
 * arriba. Cada bloque es un simbolo de la gramatica, que es lo unico que se
 * apila: en un shift el token recien leido ({@code x}) y en un reduce el no
 * terminal al que se reduce ({@code declaracion}). Debajo de la tarjeta, el
 * distintivo dice el token que se desplaza o cuantos simbolos retira la
 * reduccion. La parte inferior es una consola tipo logs con una linea por paso.</p>
 */
public class StackVisualizerPanel extends JPanel {

    // Geometria de cada columna de paso
    private static final int START_X = 20;
    private static final int COL_WIDTH = 180;
    private static final int CARD_WIDTH = COL_WIDTH - 10;
    private static final int STEP_NUM_Y = 15;
    private static final int STEP_ACTION_Y = 27;
    private static final int CARD_TOP = 32;
    private static final int CARD_PADDING = 8;
    private static final int BOX_HEIGHT = 22;
    private static final int BOX_GAP = 4;
    private static final int BOX_INSET = 6;
    private static final int BADGE_HEIGHT = 24;
    private static final int BADGE_GAP = 6;
    private static final int BOTTOM_MARGIN = 12;
    private static final int MIN_CARD_HEIGHT = 120;
    /** A partir de este numero de pasos solo se pintan las columnas visibles. */
    private static final int CLIP_THRESHOLD = 60;

    // Paleta de las tarjetas, clara sobre el fondo oscuro del dock
    private static final Color CARD_BG = new Color(254, 243, 199);
    private static final Color CARD_BORDER = new Color(217, 119, 6);
    private static final Color TOP_BOX_BG = new Color(191, 219, 254);
    private static final Color BOX_BG = new Color(254, 202, 202);
    private static final Color BOX_BORDER = new Color(140, 140, 140);
    private static final Color BOX_FG = new Color(20, 20, 20);
    private static final Color BADGE_BG = new Color(187, 247, 208);
    private static final Color BADGE_BORDER = new Color(22, 101, 52);
    private static final Color BADGE_FG = new Color(20, 83, 45);
    private static final Color EMPTY_FG = new Color(120, 120, 120);
    private static final Color SHIFT_FG = new Color(134, 239, 172);
    private static final Color REDUCE_FG = new Color(253, 186, 116);

    private List<ParseStep> steps = new ArrayList<>();
    private JPanel stackDrawPanel;
    private JTextArea logTextArea;
    private JLabel countLabel;
    private JSplitPane splitPane;

    /**
     * Creates new form StackVisualizerPanel
     */
    public StackVisualizerPanel() {
        initComponents();
        initCustomComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private void initCustomComponents() {
        setLayout(new BorderLayout());

        stackDrawPanel = new StackCanvas();
        stackDrawPanel.setBackground(UiTheme.toolWindowBg());
        stackDrawPanel.setPreferredSize(new Dimension(900, 400));

        JScrollPane stackScroll = new JScrollPane(stackDrawPanel,
                JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED,
                JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        stackScroll.setBorder(BorderFactory.createEmptyBorder());
        stackScroll.getViewport().setBackground(UiTheme.toolWindowBg());

        countLabel = new JLabel("0 pasos", SwingConstants.RIGHT);
        countLabel.setFont(UiTheme.sans(11));
        countLabel.setForeground(UiTheme.dim());
        countLabel.setBorder(UiTheme.pad(0, 8, 0, 10));

        JPanel stackBar = new JPanel(new BorderLayout());
        stackBar.setOpaque(false);
        stackBar.add(titulo("Secuencia de Estados de la Pila (Historial Completo)", 12),
                BorderLayout.WEST);
        stackBar.add(countLabel, BorderLayout.EAST);
        stackBar.setBorder(UiTheme.pad(6, 2, 4, 0));

        JPanel topContainer = new JPanel(new BorderLayout());
        topContainer.setOpaque(false);
        topContainer.add(stackBar, BorderLayout.NORTH);
        topContainer.add(stackScroll, BorderLayout.CENTER);

        logTextArea = new JTextArea();
        logTextArea.setEditable(false);
        logTextArea.setLineWrap(false);
        logTextArea.setFont(UiTheme.mono(11));
        logTextArea.setBackground(UiTheme.toolWindowBg());
        logTextArea.setForeground(UiTheme.fg());
        logTextArea.setBorder(UiTheme.pad(2, 4, 2, 4));

        JScrollPane logScroll = new JScrollPane(logTextArea);
        logScroll.setBorder(BorderFactory.createEmptyBorder());
        logScroll.getViewport().setBackground(UiTheme.toolWindowBg());

        JPanel logBar = new JPanel(new BorderLayout());
        logBar.setOpaque(false);
        logBar.add(titulo("Consola de Logs / Operaciones (shift - reduce):", 11),
                BorderLayout.WEST);
        logBar.setBorder(UiTheme.pad(4, 2, 2, 0));

        JPanel bottomContainer = new JPanel(new BorderLayout());
        bottomContainer.setOpaque(false);
        bottomContainer.add(logBar, BorderLayout.NORTH);
        bottomContainer.add(logScroll, BorderLayout.CENTER);

        splitPane = new JSplitPane(JSplitPane.VERTICAL_SPLIT, topContainer, bottomContainer);
        splitPane.setResizeWeight(0.75);
        splitPane.setDividerLocation(360);
        splitPane.setBorder(BorderFactory.createEmptyBorder());
        splitPane.setContinuousLayout(true);
        splitPane.setOneTouchExpandable(true);

        add(splitPane, BorderLayout.CENTER);
    }

    private JLabel titulo(String texto, int size) {
        JLabel label = new JLabel("  " + texto);
        label.setFont(UiTheme.sansBold(size));
        label.setForeground(UiTheme.fg());
        return label;
    }

    // ====================== API ======================

    /**
     * Carga el trazo de la pila y dibuja el historial completo, una columna por
     * paso.
     */
    public void loadSteps(List<ParseStep> nuevos) {
        steps = nuevos == null ? new ArrayList<>() : new ArrayList<>(nuevos);

        int maxDepth = 1;
        for (ParseStep st : steps) {
            maxDepth = Math.max(maxDepth, st.getPila().size());
        }

        int alto = CARD_TOP + altoTarjeta(maxDepth) + BADGE_GAP + BADGE_HEIGHT + 2 * BOTTOM_MARGIN;
        stackDrawPanel.setPreferredSize(new Dimension(
                Math.max(900, steps.size() * COL_WIDTH + 2 * START_X), alto));

        countLabel.setText(steps.size() + (steps.size() == 1 ? " paso" : " pasos"));
        updateLogs();
        stackDrawPanel.revalidate();
        stackDrawPanel.repaint();
    }

    /**
     * Numero de pasos del trazo.
     *
     * <p>Mantiene el nombre que le puso el manejador de evento generado por
     * NetBeans, que es el que lo invoca.</p>
     */
    public int getStateCount() {
        return steps.size();
    }

    /** Numero de pasos del trazo. */
    public int getStepCount() {
        return steps.size();
    }

    public void clear() {
        loadSteps(null);
    }

    /** Alto de la tarjeta: el de la pila mas profunda, con un minimo razonable. */
    private int altoTarjeta(int maxDepth) {
        return Math.max(MIN_CARD_HEIGHT, maxDepth * (BOX_HEIGHT + BOX_GAP) + 2 * CARD_PADDING);
    }

    /**
     * Escribe una linea de log por paso: numero, si desplaza o reduce, el simbolo
     * que entra en la pila y de donde sale.
     */
    private void updateLogs() {
        StringBuilder logs = new StringBuilder();
        for (ParseStep st : steps) {
            logs.append(st).append('\n');
        }
        logTextArea.setText(logs.toString());
        logTextArea.setCaretPosition(0);
    }

    // ====================== Dibujo de la pila ======================

    /** Lienzo donde se dibuja una columna por paso. */
    private class StackCanvas extends JPanel {

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            drawAllSteps(g);
        }
    }

    private void drawAllSteps(Graphics g) {
        Graphics2D g2 = (Graphics2D) g.create();
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING,
                RenderingHints.VALUE_TEXT_ANTIALIAS_ON);

        if (steps.isEmpty()) {
            g2.setColor(UiTheme.dim());
            g2.setFont(UiTheme.sans(13));
            g2.drawString("No hay pila que mostrar. Compile un archivo para ver el trazo "
                    + "de shift y reduce.", 24, 44);
            g2.dispose();
            return;
        }

        int maxDepth = 1;
        for (ParseStep st : steps) {
            maxDepth = Math.max(maxDepth, st.getPila().size());
        }
        int cardH = altoTarjeta(maxDepth);
        int badgeY = CARD_TOP + cardH + BADGE_GAP;

        for (int i = firstVisibleColumn(); i <= lastVisibleColumn(); i++) {
            drawStep(g2, steps.get(i), i, cardH, badgeY);
        }
        g2.dispose();
    }

    private void drawStep(Graphics2D g2, ParseStep state, int i, int cardH, int badgeY) {
        int x = START_X + i * COL_WIDTH;
        List<String> elementos = state.getPila();

        // Numero de paso, coloreado segun la accion
        g2.setFont(UiTheme.sansBold(12));
        g2.setColor(colorDe(state.getTipo()));
        String numero = String.valueOf(state.getNumero());
        g2.drawString(numero, x + (CARD_WIDTH - g2.getFontMetrics().stringWidth(numero)) / 2,
                STEP_NUM_Y);

        // Etiqueta shift / reduce
        g2.setFont(UiTheme.sans(9));
        String etiqueta = state.getTipo().tag();
        g2.drawString(etiqueta, x + (CARD_WIDTH - g2.getFontMetrics().stringWidth(etiqueta)) / 2,
                STEP_ACTION_Y);

        // Tarjeta del paso
        g2.setColor(CARD_BG);
        g2.fillRoundRect(x, CARD_TOP, CARD_WIDTH, cardH, 10, 10);
        g2.setColor(CARD_BORDER);
        g2.drawRoundRect(x, CARD_TOP, CARD_WIDTH, cardH, 10, 10);

        int boxW = CARD_WIDTH - 2 * BOX_INSET;

        if (elementos.isEmpty()) {
            g2.setColor(EMPTY_FG);
            g2.setFont(UiTheme.sans(11));
            FontMetrics fm = g2.getFontMetrics();
            String vacia = "Pila vacía";
            g2.drawString(vacia, x + (CARD_WIDTH - fm.stringWidth(vacia)) / 2,
                    CARD_TOP + CARD_PADDING + fm.getAscent());
        } else {
            // Contenido de la pila, con la cima arriba
            g2.setFont(UiTheme.sansBold(9));
            FontMetrics fm = g2.getFontMetrics();
            int y = CARD_TOP + CARD_PADDING;
            for (int j = elementos.size() - 1; j >= 0; j--) {
                boolean esCima = j == elementos.size() - 1;
                g2.setColor(esCima ? TOP_BOX_BG : BOX_BG);
                g2.fillRoundRect(x + BOX_INSET, y, boxW, BOX_HEIGHT, 5, 5);
                g2.setColor(BOX_BORDER);
                g2.drawRoundRect(x + BOX_INSET, y, boxW, BOX_HEIGHT, 5, 5);

                g2.setColor(BOX_FG);
                String texto = recortar(elementos.get(j), fm, boxW - 6);
                g2.drawString(texto, x + BOX_INSET + (boxW - fm.stringWidth(texto)) / 2,
                        y + (BOX_HEIGHT - fm.getHeight()) / 2 + fm.getAscent());
                y += BOX_HEIGHT + BOX_GAP;
            }
        }

        // Distintivo con el detalle de la accion: que token se desplaza o
        // cuantos simbolos retira la reduccion.
        g2.setFont(UiTheme.sans(9));
        FontMetrics fmBadge = g2.getFontMetrics();
        String detalle = recortar(distintivo(state), fmBadge, CARD_WIDTH - 12);
        g2.setColor(BADGE_BG);
        g2.fillRoundRect(x + 2, badgeY, CARD_WIDTH - 4, BADGE_HEIGHT, 6, 6);
        g2.setColor(BADGE_BORDER);
        g2.drawRoundRect(x + 2, badgeY, CARD_WIDTH - 4, BADGE_HEIGHT, 6, 6);
        g2.setColor(BADGE_FG);
        g2.drawString(detalle, x + 2 + (CARD_WIDTH - 4 - fmBadge.stringWidth(detalle)) / 2,
                badgeY + (BADGE_HEIGHT - fmBadge.getHeight()) / 2 + fmBadge.getAscent());
    }

    /**
     * Detalle que va en el distintivo de la columna: en un shift el token de la
     * gramatica que se desplaza y, si el lexema es otro, tambien el lexema; en
     * un reduce cuantos simbolos retira de la pila.
     */
    private static String distintivo(ParseStep state) {
        if (state.getTipo() == AccionPila.SHIFT) {
            String terminal = state.getTerminal();
            if (terminal == null || terminal.equals(state.getSimbolo())) {
                return state.getSimbolo();
            }
            return terminal + ": " + state.getSimbolo();
        }
        return "retira " + state.getConsumidos().size();
    }

    /** Color de la etiqueta de accion: verde para shift, naranja para reduce. */
    private static Color colorDe(AccionPila tipo) {
        return tipo == AccionPila.SHIFT ? SHIFT_FG : REDUCE_FG;
    }

    /** Recorta el texto para que quepa en el ancho dado. */
    private static String recortar(String texto, FontMetrics fm, int anchoMax) {
        if (texto == null) {
            return "";
        }
        String t = texto;
        while (t.length() > 3 && fm.stringWidth(t) > anchoMax) {
            t = t.substring(0, t.length() - 1);
        }
        return t.equals(texto) ? t : t + "..";
    }

    /** Primera columna que toca la parte visible del lienzo. */
    private int firstVisibleColumn() {
        return rangoVisible()[0];
    }

    /** Ultima columna que toca la parte visible del lienzo. */
    private int lastVisibleColumn() {
        return rangoVisible()[1];
    }

    /**
     * Rango de columnas que alcanza la parte visible del lienzo. Con muchos
     * pasos solo se pintan esas columnas para no redibujar el historial entero
     * en cada desplazamiento.
     */
    private int[] rangoVisible() {
        int ultimo = steps.size() - 1;
        Container padre = stackDrawPanel.getParent();
        if (steps.size() <= CLIP_THRESHOLD || !(padre instanceof JViewport)) {
            return new int[]{0, ultimo};
        }
        Point posicion = ((JViewport) padre).getViewPosition();
        int ancho = ((JViewport) padre).getExtentSize().width;
        int primero = Math.max(0, (posicion.x - START_X) / COL_WIDTH);
        int fin = Math.max(0, Math.min(ultimo, (posicion.x + ancho - START_X) / COL_WIDTH));
        return new int[]{primero, Math.max(primero, fin)};
    }
}
