package com.compi.frontend;

import com.compi.backend.symbols.Symbol;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 * Vista de la tabla de simbolos construida por el analizador semantico.
 *
 * Muestra una fila por simbolo con su ambito, tipo, categoria, offset y
 * detalles extra (parametros de funciones, miembros de estructuras).
 */
public class SymbolTablePanel extends javax.swing.JPanel {

    private JTable table;
    private DefaultTableModel tableModel;
    private JTextArea detailsArea;

    /**
     * Creates new form SymbolTablePanel
     */
    public SymbolTablePanel() {
        initComponents();
        initTableComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    private void initTableComponents() {
        this.setLayout(new BorderLayout());

        tableModel = new DefaultTableModel(
                new Object[]{"Símbolo", "Tipo", "Categoría", "Ámbito", "Offset", "Detalle"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        table = new JTable(tableModel);
        table.setFont(UiTheme.mono(12));
        table.setRowHeight(24);
        table.setShowGrid(true);
        table.setAutoResizeMode(JTable.AUTO_RESIZE_LAST_COLUMN);
        table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        table.getTableHeader().setFont(UiTheme.sansBold(12));
        table.getTableHeader().setReorderingAllowed(false);
        table.setBackground(UiTheme.toolWindowBg());
        table.setForeground(UiTheme.fg());
        table.setGridColor(UiTheme.separator());
        table.setSelectionBackground(UiTheme.accent());

        int[] widths = {110, 90, 90, 70, 60, 160};
        for (int i = 0; i < widths.length; i++) {
            table.getColumnModel().getColumn(i).setPreferredWidth(widths[i]);
        }

        detailsArea = new JTextArea();
        detailsArea.setEditable(false);
        detailsArea.setLineWrap(true);
        detailsArea.setWrapStyleWord(true);
        detailsArea.setFont(UiTheme.mono(12));
        detailsArea.setBackground(UiTheme.toolWindowBg());
        detailsArea.setForeground(UiTheme.fg());
        detailsArea.setBorder(UiTheme.pad(6, 8, 6, 8));
        detailsArea.setVisible(false);

        table.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                showDetails();
            }
        });

        add(new JScrollPane(table), BorderLayout.CENTER);
        add(detailsArea, BorderLayout.SOUTH);
    }

    // ====================== API ======================

    /**
     * Carga la tabla de simbolos.
     *
     * @param symbols simbolos a mostrar; null o vacio limpia la vista
     */
    public void loadSymbols(List<Symbol> symbols) {
        tableModel.setRowCount(0);
        if (symbols == null || symbols.isEmpty()) {
            detailsArea.setVisible(false);
            return;
        }
        for (Symbol s : symbols) {
            tableModel.addRow(new Object[]{
                    s.getName(),
                    s.getType() == null ? "?" : s.getType().toString(),
                    s.getCategory() == null ? "?" : s.getCategory().toString(),
                    s.isGlobal() ? "global" : "local",
                    s.getOffset(),
                    describe(s)
            });
        }
    }

    private static String describe(Symbol s) {
        StringBuilder sb = new StringBuilder();
        if (s.getParameters() != null && !s.getParameters().isEmpty()) {
            sb.append("params(");
            for (int i = 0; i < s.getParameters().size(); i++) {
                if (i > 0) {
                    sb.append(", ");
                }
                Symbol p = s.getParameters().get(i);
                sb.append(p.getName()).append(":").append(p.getType());
            }
            sb.append(')');
        }
        if (s.getMembers() != null && !s.getMembers().isEmpty()) {
            if (sb.length() > 0) {
                sb.append(' ');
            }
            sb.append("{");
            for (int i = 0; i < s.getMembers().size(); i++) {
                if (i > 0) {
                    sb.append(", ");
                }
                Symbol m = s.getMembers().get(i);
                sb.append(m.getName()).append(":").append(m.getType());
            }
            sb.append('}');
        }
        if (s.getReturnType() != null) {
            if (sb.length() > 0) {
                sb.append(' ');
            }
            sb.append("-> ").append(s.getReturnType());
        }
        return sb.length() == 0 ? "" : sb.toString();
    }

    private void showDetails() {
        int row = table.getSelectedRow();
        if (row < 0 || row >= tableModel.getRowCount()) {
            detailsArea.setVisible(false);
            return;
        }
        StringBuilder sb = new StringBuilder();
        for (int col = 0; col < tableModel.getColumnCount(); col++) {
            String value = String.valueOf(tableModel.getValueAt(row, col));
            if (value != null && !value.isBlank()) {
                sb.append(tableModel.getColumnName(col)).append(": ").append(value).append('\n');
            }
        }
        detailsArea.setText(sb.toString());
        detailsArea.setCaretPosition(0);
        detailsArea.setVisible(true);
        revalidate();
        repaint();
    }

    public JTable getTable() {
        return table;
    }

    public int getSymbolCount() {
        return tableModel.getRowCount();
    }

    /** Limpia la vista. */
    public void clear() {
        loadSymbols(null);
    }
}
