package com.compi.frontend;

import java.awt.BorderLayout;
import java.util.List;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author michael
 */
public class SymbolTablePanel extends javax.swing.JPanel {

    private JTable table;
    private DefaultTableModel tableModel;

    /**
     * Creates new form SymbolTablePanel
     */
    public SymbolTablePanel() {
        initComponents();
        initTableComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
    private void initTableComponents() {
        this.setLayout(new BorderLayout());

        String[] columns = {"Nombre", "Tipo de Dato", "Valor", "Tipo", "Rol", "Ámbito", "Línea", "Columna"};
        tableModel = new DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        table = new JTable(tableModel);
        JScrollPane scrollPane = new JScrollPane(table);

        this.add(scrollPane, BorderLayout.CENTER);
    }
/*
    public void loadSymbols(List<Symbol> symbols, TypeTable typeTable) {
        tableModel.setRowCount(0);
        if (symbols != null) {
            for (Symbol sym : symbols) {
                String scopeName = (sym.getScope() != null) ? sym.getScope().getScopeName() : "global";

                String tipoDetalle = "Primitivo";
                if (typeTable != null && sym.getType() != null) {
                    TypeInfo info = typeTable.resolveType(sym.getType());
                    if (info != null) {
                        tipoDetalle = "Tamaño: " + info.getSizeInBytes();
                    }
                }

                Object valorSimbolo = sym.getValue();
                if (valorSimbolo == null) {
                    valorSimbolo = "----";
                }

                Object[] row = {
                    sym.getName(),
                    sym.getType(),
                    valorSimbolo,
                    tipoDetalle,
                    sym.getCategory(),
                    scopeName,
                    sym.getLine(),
                    sym.getColumn()
                };
                tableModel.addRow(row);
            }
        }
    }*/
/*
    public void loadSymbols(List<Symbol> symbols) {
        loadSymbols(symbols, null);
    }*/
}
